const contact_list = [
  {
    id: 1,
    nombre: "Lucas Garcia",
    ultimo_mensaje: "Recorda que el mate sin azucar eh.",
    imagen:
      "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?fm=jpg&q=60&w=3000&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTB8fHBlcnNvbmF8ZW58MHx8MHx8fDA%3D",
    mensajes_sin_leer: 2,
    fecha_ultimo_mensaje: "14:30",
    mensajes: [
      {
        id: 1,
        autor: "Lucas Garcia",
        contenido: "Hola amigo, el cumpleaños de Jhon era hoy?.",
        fecha: "14:20",
        estatus_envio: "visto",
      },
      {
        id: 2,
        autor: "Yo",
        contenido: "Sisi, es hoy por la noche",
        fecha: "14:21",
        estatus_envio: "visto",
      },
      {
        id: 3,
        autor: "Lucas Garcia",
        contenido: "Genial, quieres que pase por ti un rato antes?",
        fecha: "14:22",
        estatus_envio: "visto",
      },
      {
        id: 4,
        autor: "Yo",
        contenido: "Me vendria genial la verdad, gracias",
        fecha: "14:23",
        estatus_envio: "visto",
      },
      {
        id: 5,
        autor: "Lucas Garcia",
        contenido: "Bien, al rededor de las 19hs estoy por tu casa",
        fecha: "14:24",
        estatus_envio: "visto",
      },
      {
        id: 6,
        autor: "Yo",
        contenido: "Dale, podemos ir tomando unos mates",
        fecha: "14:25",
        estatus_envio: "visto",
      },
      {
        id: 7,
        autor: "Lucas Garcia",
        contenido: "Sisi",
        fecha: "14:26",
        estatus_envio: "visto",
      },
      {
        id: 8,
        autor: "Lucas Garcia",
        contenido: "Recorda que el mate sin azucar eh.",
        fecha: "14:30",
        estatus_envio: "visto",
      },
    ],
  },

  {
    id: 2,
    nombre: "John Marston",
    ultimo_mensaje: "Si queres trae algo para tomar.",
    imagen:
      "https://img.magnific.com/foto-gratis/hombre-moreno-positiva-brazos-cruzados_1187-5797.jpg?semt=ais_hybrid&w=740&q=80",
    mensajes_sin_leer: 3,
    fecha_ultimo_mensaje: "08:21",
    mensajes: [
      {
        id: 1,
        autor: "John Marston",
        contenido:
          "Hola bro, el sabado festejo mi cumple y los estoy invitando a todos",
        fecha: "08:15",
        estatus_envio: "visto",
      },
      {
        id: 2,
        autor: "Yo",
        contenido: "Genial amigo, a que hora te gustaria que vaya?",
        fecha: "08:17",
        estatus_envio: "visto",
      },
      {
        id: 3,
        autor: "John Marston",
        contenido: "Tranqui, si podes veni tipo 20hs",
        fecha: "08:18",
        estatus_envio: "visto",
      },
      {
        id: 4,
        autor: "John Marston",
        contenido: "Es algo entre amigos a si que tranqui",
        fecha: "08:19",
        estatus_envio: "visto",
      },
      {
        id: 5,
        autor: "Yo",
        contenido: "Dale dale, hay que llevar algo?",
        fecha: "08:20",
        estatus_envio: "visto",
      },
      {
        id: 6,
        autor: "John Marston",
        contenido: "Gracias amigo",
        fecha: "08:21",
        estatus_envio: "visto",
      },
      {
        id: 7,
        autor: "John Marstons",
        contenido: "Tranqui no hace falta nada, ya compre todo",
        fecha: "08:21",
        estatus_envio: "visto",
      },
    ],
  },
  {
    id: 3,
    nombre: "Yoda",
    ultimo_mensaje: "Sisi voy",
    imagen:
      "https://images.unsplash.com/photo-1494790108377-be9c29b29330?fm=jpg&q=60&w=3000&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8Y2hpY2ElMjBzb25yaWVuZG98ZW58MHx8MHx8fDA%3D",
    mensajes_sin_leer: 1,
    fecha_ultimo_mensaje: "12:15",
    mensajes: [
      {
        id: 1,
        autor: "Yo",
        contenido: "Hola Jane!",
        fecha: "12:10",
        estatus_envio: "visto",
      },
      {
        id: 2,
        autor: "Jane Doe",
        contenido: "Hola, como va?",
        fecha: "12:15",
        estatus_envio: "visto",
      },
      {
        id: 3,
        autor: "Yo",
        contenido: "Vas al cumple de Jhon?",
        fecha: "12:17",
        estatus_envio: "visto",
      },
      {
        id: 4,
        autor: "Jane Doe",
        contenido: "Sisi, voy",
        fecha: "12:15",
        estatus_envio: "visto",
      },
    ],
  },
  {
    id: 4,
    nombre: "Samantha Lee",
    ultimo_mensaje: "Jajaja bueno, después te cuento",
    imagen:
      "https://static.cegos.es/content/uploads/2023/03/01165224/GettyImages-1300321639.jpg",
    mensajes_sin_leer: null,
    fecha_ultimo_mensaje: "09:35",
    mensajes: [
      {
        id: 1,
        autor: "Yo",
        contenido: "Che, ¿al final probaste ese café que te recomendé?",
        fecha: "09:28",
        estatus_envio: "visto",
      },
      {
        id: 2,
        autor: "Samantha Lee",
        contenido: "Sí jajaja, fui ayer",
        fecha: "09:30",
        estatus_envio: "visto",
      },
      {
        id: 3,
        autor: "Yo",
        contenido: "¿Y? ¿Estaba bueno o te vendí humo?",
        fecha: "09:31",
        estatus_envio: "visto",
      },
      {
        id: 4,
        autor: "Samantha Lee",
        contenido:
          "El café estaba buenísimo, pero pedí una torta que parecía de cemento",
        fecha: "09:32",
        estatus_envio: "visto",
      },
      {
        id: 5,
        autor: "Yo",
        contenido: "JAJAJA bueno, yo te recomendé el café, no la torta",
        fecha: "09:33",
        estatus_envio: "visto",
      },
      {
        id: 6,
        autor: "Samantha Lee",
        contenido: "Ya sé, no te voy a hacer responsable",
        fecha: "09:34",
        estatus_envio: "visto",
      },
      {
        id: 7,
        autor: "Yo",
        contenido: "Menos mal, ya estaba buscando abogado",
        fecha: "09:34",
        estatus_envio: "visto",
      },
      {
        id: 8,
        autor: "Samantha Lee",
        contenido: "Jajaja bueno, después te cuento",
        fecha: "09:35",
        estatus_envio: "visto",
      },
    ],
  },
];
export { contact_list };
